### ISSUE TITLE
script exceeds 2^53 MAX_NUMBER size

### ISSUE THREAD

**Issue by fabulousduck** [proj3-4standardization/iban-generator#3]
In JS, the max size of an int is 2^53. The number that is modulo'd to get the validation number often exceeds that. This can be fixed in a number of ways, and I would like input on what way is best.

* modulo resize based on validation magic number
This is gonna require a fair bit of bit level math to fix as it would need to do bounds checks aswell.

* switch to floating point
A valid solution is to do all the operations on the decimals of a float. The JS RFC states that this does have enough size to accommodate it. A concern however, as with the modulo solution, is that it can get complicated to explain what this does simply.

* import a math lib.
It is also possible to import an entire math lib to handle huge numbers. This is by far the simplest solution, but does require that the script import a 3rd party lib which is not always preferable.

Let me know what you think.

**Comment by Nick-v-L** [comment]
Solution:
```js
function calcControlNum(input){
  var ls = (parseInt(input.substring(0, 10)) % 97) * 10 ** 10;
  var rs = parseInt(input.substring(10, 20));
  var total = ls + rs;
  return 98 - total % 97;
}
```
